:api_key: 3f92aa04d7f5eac83b36095336746be0
:password: 6df48f0e553636877c209c4bbbd7fcab
:theme_id: "47"
:preview_url: https://stinfo.commercesuite.com.br/loja/loja.php?loja=1037410&opencode_theme=637b6b9ddccd6
:debug: true
