:api_key: 617aa1faae1389dcf64c7e34ab0cc845
:password: a3ed720f1ce475735ceb4a03d1bf4594
:theme_id: "47"
:preview_url: https://stinfo.commercesuite.com.br/loja/loja.php?loja=1037410&opencode_theme=637b6b9ddccd6
:debug: true
